### ISSUE TITLE
OpenVPN running on port 53 is not accessible with this plugin

### ISSUE THREAD

**Issue by krootee** [ValdikSS/openvpn-fix-dns-leak-plugin#2]
If you have OpenVPN running on port 53 then its not accessible anymore after using this plugin.

**Comment by ValdikSS** [comment]
Yeah you should be right. The workaround I'm thinking about right now is to whitelist remote server's IP. But there could be multiple IPs on one domain and multiple remote directives in config and multiple <conection> blocks…
I'll see if this can be fixed easily.

**Comment by ValdikSS** [comment]
I have another idea — allow all traffic from openvpn.exe.

**Comment by ValdikSS** [comment]
Hrmm, I have no problems connecting to UDP port 53 with old version. It seems that Windows is smart enough to bypass firewall rule for a working application.
Anyway, I fixed it a bit, please try this version and reply how it works for you.
http://ovrload.ru/f/60544_dnsleak-test.zip

**Comment by krootee** [comment]
Thanks for the effort, but 64bit version still does not work.
Same dll with OpenVPN on other port works fine (confirmed with https://www.dnsleaktest.com/).

**Comment by ValdikSS** [comment]
That's strange. Do you have TCP or UDP OpenVPN server on port 53? Can you provide more details? If you don't want to do it publicly, you can mail me at iam@valdikss.org.ru

**Comment by ValdikSS** [comment]
Please test this.
http://ovrload.ru/t/60569_testbuild.zip

**Comment by ValdikSS** [comment]
I'd be glad if you can test it today, @krootee

**Comment by krootee** [comment]
Thanks - new version seems to be working.
Will test it in more details over coming days.
And yes - its UDP over 53.

**Comment by ValdikSS** [comment]
By the way, what OS version do you use?

**Comment by krootee** [comment]
Windows 10 64-bit.

**Comment by ValdikSS** [comment]
So, does it work fine for you now?

**Comment by krootee** [comment]
Yes
